const listNavData = [
  {
    id: "palletRates",
    icon: "P",
    title: "Pallet Rates",
    description: "Manage pallet rate records",
    count: 12,
  },
  {
    id: "contactRoles",
    icon: "CR",
    title: "Contact Roles",
    description: "Manage contact role records",
    count: 8,
  },
  {
    id: "customerSegments",
    icon: "CS",
    title: "Customer Segments",
    description: "Manage customer segment records",
    count: 6,
  },
  {
    id: "contactEmails",
    icon: "CE",
    title: "Contact Emails",
    description: "Manage contact email records",
    count: 15,
  },
  {
    id: "emailSetup",
    icon: "ES",
    title: "Email Setup",
    description: "Manage email configuration",
    count: 3,
  },
  {
    id: "adjustLotNotes",
    icon: "AL",
    title: "Adjust Lot Notes",
    description: "Manage adjustment notes",
    count: 10,
  },
  {
    id: "warehouses",
    icon: "WH",
    title: "Warehouses",
    description: "Manage warehouse records",
    count: 14,
  },
  {
    id: "locations",
    icon: "LO",
    title: "Locations",
    description: "Manage warehouse locations",
    count: 28,
  },
  {
    id: "vendors",
    icon: "VE",
    title: "Vendors",
    description: "Manage vendor records",
    count: 35,
  },
  {
    id: "customers",
    icon: "CU",
    title: "Customers",
    description: "Manage customer records",
    count: 42,
  },
  {
    id: "countries",
    icon: "CO",
    title: "Countries",
    description: "Manage country records",
    count: 18,
  },
  {
    id: "states",
    icon: "ST",
    title: "States",
    description: "Manage state records",
    count: 52,
  },
  {
    id: "cities",
    icon: "CI",
    title: "Cities",
    description: "Manage city records",
    count: 210,
  },
  {
    id: "currencies",
    icon: "CU",
    title: "Currencies",
    description: "Manage currency records",
    count: 7,
  },
  {
    id: "unitsOfMeasure",
    icon: "UM",
    title: "Units of Measure",
    description: "Manage UOM records",
    count: 22,
  },
  {
    id: "commodity",
    icon: "CM",
    title: "Commodity",
    description: "Manage commodity records",
    count: 19,
  },
  {
    id: "ports",
    icon: "PO",
    title: "Ports",
    description: "Manage port records",
    count: 30,
  },
  {
    id: "freightTerms",
    icon: "FT",
    title: "Freight Terms",
    description: "Manage freight terms",
    count: 11,
  },
  {
    id: "paymentTerms",
    icon: "PT",
    title: "Payment Terms",
    description: "Manage payment terms",
    count: 9,
  },
  {
    id: "taxCodes",
    icon: "TX",
    title: "Tax Codes",
    description: "Manage tax code records",
    count: 13,
  },
  {
    id: "carrier",
    icon: "CA",
    title: "Carrier",
    description: "Manage carrier records",
    count: 16,
  },
  {
    id: "shipVia",
    icon: "SV",
    title: "Ship Via",
    description: "Manage shipping methods",
    count: 8,
  },
  {
    id: "containerTypes",
    icon: "CT",
    title: "Container Types",
    description: "Manage container types",
    count: 5,
  },
  {
    id: "reasonCodes",
    icon: "RC",
    title: "Reason Codes",
    description: "Manage reason code records",
    count: 17,
  },
  {
    id: "statusCodes",
    icon: "SC",
    title: "Status Codes",
    description: "Manage status code records",
    count: 14,
  },
];

export default listNavData;