const mockData = [
  {
    edi: "00020002",
    designer: "",
    sizeTime: "2",
    warehouse: "",
    byPick: "BPW",
    alertMessage: "N/A",
    serialNumber: "",
  },
  {
    edi: "00020003",
    designer: "",
    sizeTime: "1",
    warehouse: "",
    byPick: "Modica",
    alertMessage: "N/A",
    serialNumber: "",
  },
  {
    edi: "00020603",
    designer: "",
    sizeTime: "",
    warehouse: "RM",
    byPick: "RM",
    alertMessage: "N/A",
    serialNumber: "",
  },
  {
    edi: "00020604",
    designer: "",
    sizeTime: "1",
    warehouse: "RM",
    byPick: "RM",
    alertMessage: "N/A",
    serialNumber: "",
  },
  {
    edi: "00020605",
    designer: "",
    sizeTime: "1",
    warehouse: "RM",
    byPick: "RM",
    alertMessage: "N/A",
    serialNumber: "",
  },
  {
    edi: "00020606",
    designer: "",
    sizeTime: "2",
    warehouse: "",
    byPick: "Modica",
    alertMessage: "N/A",
    serialNumber: "",
  },
  {
    edi: "00020607",
    designer: "",
    sizeTime: "1",
    warehouse: "GKCSIGP",
    byPick: "GKCSIGP",
    alertMessage: "N/A",
    serialNumber: "",
  },
];

export default mockData;